### ISSUE TITLE
西安电子科技大学已出

### ISSUE THREAD

**Issue by RunpeiDong** [hcy226/CSSummerCamp2020#60]
人工智能学院：http://sai.xidian.edu.cn/info/1106/5161.htm
计算机科学与技术学院：https://cs.xidian.edu.cn/info/1003/9222.htm

**Comment by hcy226** [comment]
这个应该是九月预推免吧？建议直接到以下链接pull request~：

https://github.com/hcy226/CSYuTuiMian2020
